### ISSUE TITLE
awk: Argument list too long

### ISSUE THREAD

**Issue by VaninaTonzo** [palfalvi/badirater#1]
Hi! I was trying to use badirater to collect and analyse my results from badirate. I am working with a big dataset, around 60000 OGs but I keep getting the typical  "awk: Argument list too long" error. I tried to fix it and run the script in the cluster but I am still getting the same argument.

Is there any solution when working with this kind of big datasets?

Best,

**Comment by palfalvi** [comment]
Hi,

Which function gave this error? I believe only bd_collect() uses awk. 
Anyway, I do not know an exact solution, but you can try to split the setup_table and collect into several files, then manually merge. Alternatively you can try to rewrite the code with xargs. I hope you can solve this issue.

Best
Gergo
